/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkg2dlongbooty;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author bpb
 */
public class G extends javax.swing.JFrame {

 //   libray p = new libray();
      libray p;
   
DefaultListModel listModel;
DefaultListModel listModel2;
    /**
     * Creates new form G
     */
    public G() throws IOException, ClassNotFoundException  {
        this.p = (libray) libray.deserialize("C:/Users/bpb/Desktop/save/G.txt");
         listModel = new DefaultListModel();
         listModel2 = new DefaultListModel();
   
         p.THug();
      
        initComponents();
    }
    public  void  SearchTitle(){
       listModel.clear();
   ArrayList<String> temp =   p.Names4Gui();
   listModel.clear();
   for(int x =0; x < temp.size(); x++){
      System.out.println(temp.get(x));
       listModel.add(x, temp.get(x));
   }
   }
    public void SearchIsbn(){
        
        ArrayList<String> temp = p.isbn4Gui();
        listModel.clear();
        for(int x =0; x < temp.size(); x++){
       listModel.add(x, temp.get(x));
   }
        
    }
      public  void  SearchSub(){
      
   ArrayList<String> temp =   p.subject4Gui();
   listModel.clear();
   for(int x =0; x < temp.size(); x++){
       listModel.add(x, temp.get(x));
   }
   
   }
           public  void  SearchDate(){
      
   ArrayList<String> temp =   p.Date4Gui();
   listModel.clear();
   for(int x =0; x < temp.size(); x++){
       listModel.add(x, temp.get(x));
   }
           }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(listModel);
        choice1 = new java.awt.Choice();
        Name = new javax.swing.JTextField();
        Author = new javax.swing.JTextField();
        Subject = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Publisher = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList(listModel2);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        choice1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                choice1ComponentShown(evt);
            }
        });
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });
        choice1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                choice1PropertyChange(evt);
            }
        });

        Name.setText("Title");

        Author.setText("Author");
        Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorActionPerformed(evt);
            }
        });

        Subject.setText("Subject");

        Date.setText("Date");

        ISBN.setText("ISBN");

        jButton1.setText("AddBook");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Publisher.setText("Publisher");

        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jMenu1.setText("File");

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Author)
                    .addComponent(Subject)
                    .addComponent(Date)
                    .addComponent(ISBN)
                    .addComponent(Name)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addComponent(Publisher, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Subject, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        choice1.addItem("Title");
        //should sort a-z
        choice1.addItem("ISBN");
        // first to last
        choice1.addItem("Subject");
        // sort a-z
        choice1.addItem("Date");
        // first to last
        SearchTitle();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
         int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
        p =    (libray) libray.deserialize(file.getAbsolutePath());
        
  
          // What to do with the file, e.g. display it in a TextArea
         
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }    catch (ClassNotFoundException ex) {
                 Logger.getLogger(G.class.getName()).log(Level.SEVERE, null, ex);
             }
    } else {
        System.out.println("File access cancelled by user.");
    }

    }//GEN-LAST:event_OpenActionPerformed

    private void choice1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_choice1PropertyChange
      System.out.println( choice1.getSelectedItem());
    }//GEN-LAST:event_choice1PropertyChange

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
 System.out.println( choice1.getSelectedItem());  
if("Title".equals(choice1.getSelectedItem())) {
    SearchTitle();
 }
else if("ISBN".equals(choice1.getSelectedItem())){
    SearchIsbn();
    
} 
else if("Subject".equals(choice1.getSelectedItem())){
    SearchSub();
}
    else if("Date".equals(choice1.getSelectedItem())){
    SearchDate();
    
} 
// TODO add your handling code here:
    }//GEN-LAST:event_choice1ItemStateChanged

    private void choice1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_choice1ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_choice1ComponentShown

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
JFileChooser cho = new JFileChooser();
int retrival = cho.showSaveDialog(null);
 if (retrival == JFileChooser.APPROVE_OPTION) {
    try {
        libray.serialize(p, cho.getSelectedFile().getAbsolutePath().toString());
    } catch (IOException ex) {
        Logger.getLogger(G.class.getName()).log(Level.SEVERE, null, ex);
    }
 }

          
    }//GEN-LAST:event_SaveActionPerformed

    private void AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (Author.getText() != null && !"Author".equals(Author.getText()) ){
        if(Date.getText()!= null && ! "Date".equals(Date.getText())){
            if(Name.getText()!= null && ! "Name".equals(Name.getText())){
                if(Subject.getText()!= null && ! "Subject".equals(Subject.getText())){
                    if(ISBN.getText()!= null && ! "Name".equals(ISBN.getText())){
                      int Dates = Integer.parseInt(Date.getText()); 
                      int Isbn = Integer.parseInt(ISBN.getText());
         Book a = new Book(Name.getText(), Publisher.getText(), Dates, Isbn, true );
         a.SetSub(Subject.getText());
         p.g.add(a);
         System.out.println("you did it asshole");
                
        }
    }
    }
    }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
int x = (jList1.getSelectedIndex());
listModel2.clear();
if (choice1.getSelectedItem().equals("Title")){
    String f = p.TooString(x);
listModel2.add(0, f);

}

        
    }//GEN-LAST:event_jList1ValueChanged
    
    

 



public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new G().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(G.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(G.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Name;
    private javax.swing.JMenuItem Open;
    private javax.swing.JTextField Publisher;
    private javax.swing.JMenuItem Save;
    private javax.swing.JTextField Subject;
    private java.awt.Choice choice1;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
